version: "3.9"
services:
  evoeapi:
    container_name: evoeapi
    image: maora/evoeapi
    build: .
    ports:
      - 3000:3000
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPORT=5432
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
